name: arthuriq-backend-beta

services:
  api:
    build: .
    container_name: arthuriq_beta_api
    restart: unless-stopped
    env_file:
      - .env
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.arthuriqbeta.entrypoints=websecure"
      - "traefik.http.routers.arthuriqbeta.rule=Host(`api-beta.arthuriq.com`)"
      - "traefik.http.routers.arthuriqbeta.tls.certresolver=letsencrypt"
      - "traefik.http.services.arthuriqbeta.loadbalancer.server.port=3002"

networks:
  default:
    name: shelfwise_default
    external: true
