name: shelfwise

services:
  api:
    build: .
    container_name: shelfwise_api
    restart: unless-stopped
    env_file:
      - .env
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.shelfwise.entrypoints=websecure"
      - "traefik.http.routers.shelfwise.rule=Host(`api.arthuriq.com`)"
      - "traefik.http.routers.shelfwise.tls.certresolver=letsencrypt"
      - "traefik.http.services.shelfwise.loadbalancer.server.port=3002"

networks:
  default:
    name: shelfwise_default
    ipam:
      config:
        - subnet: 172.30.0.0/16
